This program is a sideprogram for the image enhancer super resolution GAN. \
It resizes the image dataset into low and high resolution images, which are used for training and testing the GAN.\

The dataset is taken from: http://press.liacs.nl/mirflickr/mirdownload.html

In [2]:
import cv2
import numpy as np
import os
import matplotlib.pyplot as plt

In [3]:
# This is the directory of the image dataset
train_dir = "image dataset/mirflickr25k"


In [18]:
img_ar = cv2.imread("image dataset/mirflickr25k/original_images/im10897.jpg")
print(img_ar)

[[[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 4  6  6]
  [ 4  6  6]
  [ 4  6  6]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 4  6  6]
  [ 4  6  6]
  [ 4  6  6]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 5  7  7]
  [ 4  6  6]
  [ 4  6  6]]

 ...

 [[17 19 19]
  [14 22 21]
  [16 22 21]
  ...
  [15 26 24]
  [14 25 23]
  [13 24 22]]

 [[14 19 18]
  [13 24 22]
  [16 24 23]
  ...
  [35 48 46]
  [35 48 46]
  [34 47 45]]

 [[19 27 26]
  [17 31 29]
  [20 33 31]
  ...
  [16 22 21]
  [18 24 23]
  [16 22 21]]]


In [6]:

for img in os.listdir("image dataset/mirflickr25k/original_images"):
    print("Image name: ", img)

    img_array = cv2.imread("image dataset/mirflickr25k/original_images/" + img)
    
    # print("Image array: ", img_array)
    img_array = cv2.resize(img_array, (128,128))
    lr_img_array = cv2.resize(img_array,(32,32))
    cv2.imwrite("image dataset/mirflickr25k/hr_images/" + img, img_array)
    cv2.imwrite("image dataset/mirflickr25k/lr_images/"+ img, lr_img_array)

Image name:  im1.jpg
Image name:  im10.jpg
Image name:  im100.jpg
Image name:  im1000.jpg
Image name:  im10000.jpg
Image name:  im10001.jpg
Image name:  im10002.jpg
Image name:  im10003.jpg
Image name:  im10004.jpg
Image name:  im10005.jpg
Image name:  im10006.jpg
Image name:  im10007.jpg
Image name:  im10008.jpg
Image name:  im10009.jpg
Image name:  im1001.jpg
Image name:  im10010.jpg
Image name:  im10011.jpg
Image name:  im10012.jpg
Image name:  im10013.jpg
Image name:  im10014.jpg
Image name:  im10015.jpg
Image name:  im10016.jpg
Image name:  im10017.jpg
Image name:  im10018.jpg
Image name:  im10019.jpg
Image name:  im1002.jpg
Image name:  im10020.jpg
Image name:  im10021.jpg
Image name:  im10022.jpg
Image name:  im10023.jpg
Image name:  im10024.jpg
Image name:  im10025.jpg
Image name:  im10026.jpg
Image name:  im10027.jpg
Image name:  im10028.jpg
Image name:  im10029.jpg
Image name:  im1003.jpg
Image name:  im10030.jpg
Image name:  im10031.jpg
Image name:  im10032.jpg
Image name:  